### PR TITLE
ansible playbook (revised and reduced)

### PR DESCRIPTION
**Pull request by scottsb**
Based on branch from #1 but reworked and updated to pull into the correct branch.

### CODE REVIEW

**Comment by immanetize** [comment]
Functional and succinctly executed, +1

**Comment by b-harper** [comment]
Many thanks.

**Comment by samjsharpe** [comment]
:+1: :shipit:

**Comment by b-harper** [comment]
@scottsb,

Thanks for taking the time to submit this pull request.    

@immanetize, @samjsharpe,

Thanks for the feedback.

**Pull request merged**
